Account setting page
Rectle/rectle-ui pull request #10
Opened 2022-11-22 14:39 UTC by Michaqu11

2022-11-22 14:53 UTC, Madek1 requested changes
podbij wersje

2022-11-22 14:53 UTC, Madek1 commented on src/components/settingElements/SettingAccount.vue
> +          @click="changeJWT"
chyba mozna dodac watch na buttonJWT

2022-11-22 14:53 UTC, Madek1 commented on src/components/settingElements/SettingAccount.vue
> +const buttonJWT: string = ref(LocalStorage.getItem('JWT') ? t('accountSettings.toggleJWT.trueValue') : t('accountSettings.toggleJWT.falseValue'))
po co nam wlasne nazwy? Nie lepiej uzyc po prostu true/false?

2022-11-22 15:09 UTC, Michaqu11 commented on src/components/settingElements/SettingAccount.vue
> +const buttonJWT: string = ref(LocalStorage.getItem('JWT') ? t('accountSettings.toggleJWT.trueValue') : t('accountSettings.toggleJWT.falseValue'))
Teoretycznie tak, ale tak można fajnie label wyświetlić(enable/disable).

2022-11-22 15:32 UTC, Michaqu11 commented on src/components/settingElements/SettingAccount.vue
> +          @click="changeJWT"
watch nie działał. Zamieniłem na event @update:model-value, który ty używasz w AuthLayout.

2022-11-24 19:03 UTC, PiotrKopecki approved these changes

2022-11-26 18:59 UTC, PiotrKopecki approved these changes

2022-11-27 23:07 UTC, Madek1 approved these changes

2022-11-27 23:07 UTC, Madek1 commented on src/components/settingElements/SettingAccount.vue
> +    LocalStorage.set('JWT', true);
zapisuj w JWT token ze stora

2022-11-27 23:08 UTC, merged