Setup code page
Rectle/rectle-ui pull request #11
Opened 2022-11-26 18:30 UTC by Michaqu11

2022-11-30 08:55 UTC, Madek1 requested changes
zapulluj zmiany z maina

2022-11-30 08:55 UTC, Madek1 commented on src/components/CodeComponent.vue
> +function onSubmit () {
arrow function

2022-11-30 08:55 UTC, Madek1 commented on src/components/CodeComponent.vue
> +    console.log('file was uploaded', file)
usun

2022-11-30 23:38 UTC, PiotrKopecki approved these changes

2022-12-01 13:59 UTC, Madek1 approved these changes

2022-12-01 13:59 UTC, Madek1 commented on src/components/CodeComponent.vue
> +      <div>
po co ten div?

2022-12-01 22:04 UTC, merged