Code editor page
Rectle/rectle-ui pull request #14
Opened 2022-12-27 00:36 UTC by Michaqu11

2022-12-27 18:05 UTC, PiotrKopecki approved these changes

2023-01-06 13:06 UTC, Madek1 requested changes

2023-01-06 13:06 UTC, Madek1 commented on package.json
> +    "simple-code-editor": "^1.2.2",
potrzebujemy to?

2023-01-06 13:06 UTC, Madek1 commented on package.json
> +    "prismjs": "^1.29.0",
potrzebujemy to?

2023-01-06 13:06 UTC, Madek1 commented on package.json
> +    "ace-code": "^1.13.1",
sa zainstalowane 3 wersje tej bilbioteki, wybierz 1 ktora potrzebujemy

2023-01-06 13:06 UTC, Madek1 commented on package.json
> +    "@dans98/vue-prism-editor": "^0.5.2",
potrzebujemy to?

2023-01-06 13:06 UTC, Madek1 commented on src/components/CodeEditorComponent.vue
> +        style="height: 300px" />
uzyj klasy do stylowania

2023-01-06 13:06 UTC, Madek1 commented on src/components/CodeEditorComponent.vue
> +let content = ref<string>(SessionStorage.getItem('code') ?? 'console.log("hello ok.")');
usun console loga

2023-01-06 13:06 UTC, Madek1 commented on src/components/CodeEditorComponent.vue
> +const lang = ref<string>('javascript');
chyba powinien być python?

2023-01-06 17:33 UTC, Michaqu11 commented on package.json
> +    "prismjs": "^1.29.0",
nie

2023-01-06 17:33 UTC, Michaqu11 commented on package.json
> +    "@dans98/vue-prism-editor": "^0.5.2",
nie

2023-01-06 17:33 UTC, Michaqu11 commented on package.json
> +    "simple-code-editor": "^1.2.2",
nie

2023-01-06 17:51 UTC, Madek1 approved these changes

2023-01-06 17:52 UTC, merged