Project overview
Rectle/rectle-ui pull request #29
Opened 2023-06-01 13:14 UTC by Michaqu11

2023-06-01 13:44 UTC, PiotrKopecki approved these changes

2023-06-05 16:52 UTC, Madek1 requested changes

2023-06-05 16:52 UTC, Madek1 commented on src/components/project-overview/details/project-details-approacheCard.vue
> +        :name="status == 'done' ? 'o_check_circle' : 'o_pending'"
`===` + moze daj 'done' jako jakis typ

2023-06-05 16:52 UTC, Madek1 commented on src/components/project-overview/details/project-details-approacheCard.vue
> +        :color="status == 'done' ? 'green' : 'orange'"
jak powyzej

2023-06-05 16:52 UTC, Madek1 commented on src/components/project-overview/project-title.vue
> +      :class="index == '0' ? 'q-ml-none' : ''"
`index === 0` ?

2023-06-05 16:52 UTC, Madek1 commented on src/components/project-overview/project-title.vue
> +      :class="index == '0' ? 'q-ml-none' : ''"
`:class="{'q-ml-none': index === 0}"`

2023-06-05 19:56 UTC, merged