About page
Rectle/rectle-ui pull request #42
Opened 2023-07-30 23:11 UTC by Michaqu11

2023-08-05 14:43 UTC, PiotrKopecki approved these changes

2023-08-07 18:35 UTC, Madek1 requested changes

2023-08-07 18:35 UTC, Madek1 commented on src/components/settings/AboutSetting.vue
> +const editor = ref(locale.value == 'en-US' ? en : pl);
Tak samoj ak przy poprzednich 2 PR

2023-08-07 20:36 UTC, bartkalit approved these changes

2023-08-07 21:16 UTC, merged